# Generated by Django 3.1.5 on 2021-02-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APS_app', '0005_auto_20210205_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_donator',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blood_donator',
            name='medical_docs',
            field=models.ImageField(blank=True, upload_to='medical_docs_pic'),
        ),
        migrations.AlterField(
            model_name='blood_donator',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
